data:
  train_files: data/llm_mixup/train.json
  val_files: data/llm_mixup/test.json
  prompt_key: input
  answer_key: output
  image_key: images
  video_key: videos
  image_dir: null
  video_fps: 2.0
  max_prompt_length: 2400
  max_response_length: 2400
  rollout_batch_size: 128  
  mini_rollout_batch_size: null  
  val_batch_size: 256
  format_prompt: ./examples/format_prompt/mixup.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 262144
  max_pixels: 4194304
  filter_overlong_prompts: false

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: false  # dapo filter groups
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99

worker:
  actor:
    global_batch_size: 16  # equivalent to verl's actor.ppo_mini_batch_size
    micro_batch_size_per_device_for_update: 4  # equivalent to verl's actor.ppo_micro_batch_size_per_gpu
    micro_batch_size_per_device_for_experience: 16  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: sft/sft_output/qwen_2_5_1_5b_cold_start/checkpoint-35069
      enable_gradient_checkpointing: true
      trust_remote_code: true
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 4
    temperature: 1.0
    top_p: 1.0
    limit_images: 0
    gpu_memory_utilization: 0.85
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1  # 1 GPU
    disable_tqdm: false
    val_override_config:
      temperature: 0.6
      top_p: 0.95
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: batch  
    reward_function: ./examples/reward_function/llm_mixup_bayes.py:compute_score
    num_cpus: 4  
    num_gpus: 0.5 
    
    reward_function_kwargs:
      knn_bayes_lib_path: EasyR1/emb_lib 
      # Expected file structure:
      # EasyR1/emb_lib/
      # ├── qa/
      # │   ├── B_emb.npy        
      # │   ├── B_scores.npy     
      # │   ├── meta.json        
      # │   └── nn_index.pkl     
      # ├── mcq/                 
      # ├── cs/                  
      # ├── paragraph/           
      # └── tfq/                
      
      # Quality scoring configuration
      quality_scoring:
          k_neighbors: 16  # Number of neighbors for KNN retrieval
          enable_batch_scoring: true  # Enable batch scoring optimization
          batch_size: 16  # Batch size for batch scoring
      
      # BGE-M3 embedding model for both quality and alignment scoring
      embedding_model_path: BAAI/bge-m3
      
      # Multi-task reward weights
      weights:
        quality: 0.5   
        alignment: 0.4  
        format: 0.1     
      
      # Debug configuration
      debug_mode: false  # Set to true to enable detailed logging of task-specific scoring
      
      # Task-specific configuration
      task_specific_config:
        qa_mixup:
          quality_weight_override: null  
          alignment_weight_override: null
          format_weight_override: null
        cs_mixup:
          quality_weight_override: null   
          alignment_weight_override: null
          format_weight_override: null
        mcq_mixup:
          quality_weight_override: null   
          alignment_weight_override: null
          format_weight_override: null
        para_mixup:
          quality_weight_override: null   
          alignment_weight_override: null
          format_weight_override: null
        tfq_mixup:
          quality_weight_override: null
          alignment_weight_override: null
          format_weight_override: null

trainer:
  total_epochs: 1
  max_steps: null
  project_name: easy_r1
  experiment_name: qwen_mixup_1_5b_new_grpo_test  
  logger: ["console"]       #["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 2  # 1 GPU for training
  max_try_make_batch: 20  # -1 means no limit
  val_freq: -1  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 5  # -1 to disable
  save_limit: 1  # -1 to disable
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true